RegisterNetEvent("time:client")
AddEventHandler("time:client", function(time, minutes)
    NetworkOverrideClockTime(time, minutes, 0)
end)
RegisterNetEvent("Extra-sunny:client")
AddEventHandler("Extra-sunny:client", function()
    SetWeatherTypePersist("EXTRASUNNY")
    SetWeatherTypeNowPersist("EXTRASUNNY")
    SetWeatherTypeNow("EXTRASUNNY")
    SetOverrideWeather("EXTRASUNNY")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Clear:client")
AddEventHandler("Clear:client", function()
    SetWeatherTypePersist("CLEAR")
    SetWeatherTypeNowPersist("CLEAR")
    SetWeatherTypeNow("CLEAR")
    SetOverrideWeather("CLEAR")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Clouds:client")
AddEventHandler("Clouds:client", function()
    SetWeatherTypePersist("CLOUDS")
    SetWeatherTypeNowPersist("CLOUDS")
    SetWeatherTypeNow("CLOUDS")
    SetOverrideWeather("CLOUDS")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Smog:client")
AddEventHandler("Smog:client", function()
    SetWeatherTypePersist("SMOG")
    SetWeatherTypeNowPersist("SMOG")
    SetWeatherTypeNow("SMOG")
    SetOverrideWeather("SMOG")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Foggy:client")
AddEventHandler("Foggy:client", function()
    SetWeatherTypePersist("FOGGY")
    SetWeatherTypeNowPersist("FOGGY")
    SetWeatherTypeNow("FOGGY")
    SetOverrideWeather("FOGGY")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Overcast:client")
AddEventHandler("Overcast:client", function()
    SetWeatherTypePersist("OVERCAST")
    SetWeatherTypeNowPersist("OVERCAST")
    SetWeatherTypeNow("OVERCAST")
    SetOverrideWeather("OVERCAST")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Raining:client")
AddEventHandler("Raining:client", function()
    SetWeatherTypePersist("RAIN")
    SetWeatherTypeNowPersist("RAIN")
    SetWeatherTypeNow("RAIN")
    SetOverrideWeather("RAIN")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Thunderstorm:client")
AddEventHandler("Thunderstorm:client", function()
    SetWeatherTypePersist("THUNDER")
    SetWeatherTypeNowPersist("THUNDER")
    SetWeatherTypeNow("THUNDER")
    SetOverrideWeather("THUNDER")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Clearing:client")
AddEventHandler("Clearing:client", function()
    SetWeatherTypePersist("CLEARING")
    SetWeatherTypeNowPersist("CLEARING")
    SetWeatherTypeNow("CLEARING")
    SetOverrideWeather("CLEARING")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Neutral:client")
AddEventHandler("Neutral:client", function()
    SetWeatherTypePersist("NEUTRAL")
    SetWeatherTypeNowPersist("NEUTRAL")
    SetWeatherTypeNow("NEUTRAL")
    SetOverrideWeather("NEUTRAL")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Blizzard:client")
AddEventHandler("Blizzard:client", function()
    SetWeatherTypePersist("BLIZZARD")
    SetWeatherTypeNowPersist("BLIZZARD")
    SetWeatherTypeNow("BLIZZARD")
    SetOverrideWeather("BLIZZARD")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Snowlight:client")
AddEventHandler("Snowlight:client", function()
    SetWeatherTypePersist("SNOWLIGHT")
    SetWeatherTypeNowPersist("SNOWLIGHT")
    SetWeatherTypeNow("SNOWLIGHT")
    SetOverrideWeather("SNOWLIGHT")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Christmas:client")
AddEventHandler("Christmas:client", function()
    SetWeatherTypePersist("XMAS")
    SetWeatherTypeNowPersist("XMAS")
    SetWeatherTypeNow("XMAS")
    SetOverrideWeather("XMAS")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Snowing:client")
AddEventHandler("Snowing:client", function()
    SetWeatherTypePersist("SNOW")
    SetWeatherTypeNowPersist("SNOW")
    SetWeatherTypeNow("SNOW")
    SetOverrideWeather("SNOW")
    SetForcePedFootstepsTracks(true)
end)
RegisterNetEvent("Halloween:client")
AddEventHandler("Halloween:client", function()
    SetWeatherTypePersist("HALLOWEEN")
    SetWeatherTypeNowPersist("HALLOWEEN")
    SetWeatherTypeNow("HALLOWEEN")
    SetOverrideWeather("HALLOWEEN")
    SetForcePedFootstepsTracks(true)
end)

RegisterNetEvent("weatherclient")
AddEventHandler("weatherclient", function(weather)
    if tonumber(weather) == -1750463879 then 
        SetWeatherTypePersist("EXTRASUNNY")
        SetWeatherTypeNowPersist("EXTRASUNNY")
        SetWeatherTypeNow("EXTRASUNNY")
        SetOverrideWeather("EXTRASUNNY")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 916995460 then
        SetWeatherTypePersist("CLEAR")
        SetWeatherTypeNowPersist("CLEAR")
        SetWeatherTypeNow("CLEAR")
        SetOverrideWeather("CLEAR")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 821931868 then 
        SetWeatherTypePersist("CLOUDS")
        SetWeatherTypeNowPersist("CLOUDS")
        SetWeatherTypeNow("CLOUDS")
        SetOverrideWeather("CLOUDS")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 282916021 then 
        SetWeatherTypePersist("SMOG")
        SetWeatherTypeNowPersist("SMOG")
        SetWeatherTypeNow("SMOG")
        SetOverrideWeather("SMOG")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == -1368164796 then 
        SetWeatherTypePersist("FOGGY")
        SetWeatherTypeNowPersist("FOGGY")
        SetWeatherTypeNow("FOGGY")
        SetOverrideWeather("FOGGY")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == -1148613331 then 
        SetWeatherTypePersist("OVERCAST")
        SetWeatherTypeNowPersist("OVERCAST")
        SetWeatherTypeNow("OVERCAST")
        SetOverrideWeather("OVERCAST")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 1420204096 then 
        SetWeatherTypePersist("RAIN")
        SetWeatherTypeNowPersist("RAIN")
        SetWeatherTypeNow("RAIN")
        SetOverrideWeather("RAIN")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == -1233681761 then 
        SetWeatherTypePersist("THUNDER")
        SetWeatherTypeNowPersist("THUNDER")
        SetWeatherTypeNow("THUNDER")
        SetOverrideWeather("THUNDER")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 1840358669 then 
        SetWeatherTypePersist("CLEARING")
        SetWeatherTypeNowPersist("CLEARING")
        SetWeatherTypeNow("CLEARING")
        SetOverrideWeather("CLEARING")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == -1530260698 then
        SetWeatherTypePersist("NEUTRAL")
        SetWeatherTypeNowPersist("NEUTRAL")
        SetWeatherTypeNow("NEUTRAL")
        SetOverrideWeather("NEUTRAL")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 669657108 then 
        SetWeatherTypePersist("BLIZZARD")
        SetWeatherTypeNowPersist("BLIZZARD")
        SetWeatherTypeNow("BLIZZARD")
        SetOverrideWeather("BLIZZARD")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == 603685163 then 
        SetWeatherTypePersist("SNOWLIGHT")
        SetWeatherTypeNowPersist("SNOWLIGHT")
        SetWeatherTypeNow("SNOWLIGHT")
        SetOverrideWeather("SNOWLIGHT")
        SetForcePedFootstepsTracks(true)
    end 
    if tonumber(weather) == 273223690 then 
        SetWeatherTypePersist("SNOW")
        SetWeatherTypeNowPersist("SNOW")
        SetWeatherTypeNow("SNOW")
        SetOverrideWeather("SNOW")
        SetForcePedFootstepsTracks(true)
    end
    if tonumber(weather) == -1429616491 then 
        SetWeatherTypePersist("XMAS")
        SetWeatherTypeNowPersist("XMAS")
        SetWeatherTypeNow("XMAS")
        SetOverrideWeather("XMAS")
        SetForcePedFootstepsTracks(true)
    end
end)

RegisterNetEvent("notif:succes:weather:enregistre")
AddEventHandler("notif:succes:weather:enregistre", function()
    if Config["notif"].okoknotify then 
        TriggerEvent('okokNotify:Alert', "SUCCESS", "Vous venez de d'enregistrer la météo dans la bdd", 5000, 'success')
    else 
        ESX.ShowAdvancedNotification("Notification","~g~Succes", "Vous venez de d'enregistrer la météo dans la bdd ", "CHAR_BANK_MAZE", 1)
    end
end)

RegisterNetEvent("erreur:renitialise:weather")
AddEventHandler("erreur:renitialise:weather", function()
    if Config["notif"].okoknotify then 
        TriggerEvent('okokNotify:Alert', "Erreur", "Vous ne pouvez pas renitialisé la météo car aucune météo a été enregistrée en bdd ! ", 5000, 'error')
    else 
        ESX.ShowAdvancedNotification("Notification","~r~Erreur", "Vous ne pouvez pas renitialisé la météo car aucune météo a été enregistrée en bdd ! ", NotifPicture, 1)
    end
end)

RegisterNetEvent("sucess:renitialise:weather")
AddEventHandler("sucess:renitialise:weather", function()
    if Config["notif"].okoknotify then 
        TriggerEvent('okokNotify:Alert', "SUCCESS", "Vous venez de renitialisé la météo !", 5000, 'success')
    else 
        ESX.ShowAdvancedNotification("Notification","~g~Succes", "Vous venez de renitialisé la météo !", "CHAR_BANK_MAZE", 1)
    end
end)
